In [5]:
#evaluar la eficiencia del código
import time
inicio = time.time()
#dormir 0.5 segundos
time.sleep(0.5)
fin=time.time()
print(fin-inicio)


0.5000708103179932


In [6]:
#otra forma
from datetime import timedelta
inicio=time.monotonic()
#dormir
time.sleep(1)
fin=time.monotonic()
print(timedelta(seconds=fin-inicio))

0:00:01.016000


In [2]:
print("Prueba 1")

Prueba 1


In [1]:
#importar andas y un set de datos
import pandas as pd
import numpy as np
#cargar los datos desde un csv
df=pd.read_csv("C:/Users/David/Desktop/U_en_linea/Cursos de Python/Linkedin/base_datos_2008.csv")

In [7]:
#explorar los datos
df.head()

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0  2008      1           3          4   2003.0        1955   2211.0   
1  2008      1           3          4    754.0         735   1002.0   
2  2008      1           3          4    628.0         620    804.0   
3  2008      1           3          4    926.0         930   1054.0   
4  2008      1           3          4   1829.0        1755   1959.0   

   CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
0        2225            WN        335  ...    4.0      8.0          0   
1        1000            WN       3231  ...    5.0     10.0          0   
2         750            WN        448  ...    3.0     17.0          0   
3        1100            WN       1746  ...    3.0      7.0          0   
4        1925            WN       3920  ...    3.0     10.0          0   

   CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
0               NaN         0           NaN          NaN      NaN   
1               NaN         0           NaN          NaN      NaN   
2               NaN         0           NaN          NaN      NaN   
3               NaN         0           NaN          NaN      NaN   
4               NaN         0           2.0          0.0      0.0   

   SecurityDelay  LateAircraftDelay  
0            NaN                NaN  
1            NaN                NaN  
2            NaN                NaN  
3            NaN                NaN  
4            0.0               32.0  

[5 rows x 29 columns]

In [8]:
#mostrar las últimas 5 filas
df.tail()

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
7009723  2008     12          13          6   1002.0         959   1204.0   
7009724  2008     12          13          6    834.0         835   1021.0   
7009725  2008     12          13          6    655.0         700    856.0   
7009726  2008     12          13          6   1251.0        1240   1446.0   
7009727  2008     12          13          6   1110.0        1103   1413.0   

         CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
7009723        1150            DL       1636  ...    6.0     45.0          0   
7009724        1023            DL       1637  ...    5.0     23.0          0   
7009725         856            DL       1638  ...   24.0     12.0          0   
7009726        1437            DL       1639  ...   13.0     13.0          0   
7009727        1418            DL       1641  ...    8.0     11.0          0   

         CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
7009723               NaN         0           NaN          NaN      NaN   
7009724               NaN         0           NaN          NaN      NaN   
7009725               NaN         0           NaN          NaN      NaN   
7009726               NaN         0           NaN          NaN      NaN   
7009727               NaN         0           NaN          NaN      NaN   

         SecurityDelay  LateAircraftDelay  
7009723            NaN                NaN  
7009724            NaN                NaN  
7009725            NaN                NaN  
7009726            NaN                NaN  
7009727            NaN                NaN  

[5 rows x 29 columns]

In [9]:
#reordenar los datos
df.sample(frac=1)

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
3231732  2008      6          10          2   1040.0        1033   1345.0   
2005293  2008      4          28          1   1231.0        1232   2008.0   
1110113  2008      2          11          1   1121.0        1126   1412.0   
3304867  2008      6          23          1   1330.0        1335   1502.0   
621929   2008      2           7          4    605.0         605    722.0   
...       ...    ...         ...        ...      ...         ...      ...   
1669030  2008      3          19          3   1440.0        1445   2002.0   
4214149  2008      7           5          6   1529.0        1500   1745.0   
4506188  2008      8          10          7    623.0         625    800.0   
1752876  2008      3           5          3    738.0         740   1104.0   
6961635  2008     12          15          1   1255.0        1259   1427.0   

         CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
3231732        1353            UA        532  ...    5.0     13.0          0   
2005293        2022            UA         34  ...    4.0     10.0          0   
1110113        1404            AS        501  ...    7.0     19.0          0   
3304867        1513            DL       1707  ...   10.0     13.0          0   
621929          725            WN       1525  ...    7.0     14.0          0   
...             ...           ...        ...  ...    ...      ...        ...   
1669030        2020            AA        522  ...    7.0      9.0          0   
4214149        1717            DL       1057  ...    7.0     15.0          0   
4506188         813            US       1093  ...   10.0     11.0          0   
1752876        1101            CO        642  ...    6.0     32.0          0   
6961635        1419            B6         27  ...   11.0     17.0          0   

         CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
3231732               NaN         0           NaN          NaN      NaN   
2005293               NaN         0           NaN          NaN      NaN   
1110113               NaN         0           NaN          NaN      NaN   
3304867               NaN         0           NaN          NaN      NaN   
621929                NaN         0           NaN          NaN      NaN   
...                   ...       ...           ...          ...      ...   
1669030               NaN         0           NaN          NaN      NaN   
4214149               NaN         0           0.0          6.0      0.0   
4506188               NaN         0           NaN          NaN      NaN   
1752876               NaN         0           NaN          NaN      NaN   
6961635               NaN         0           NaN          NaN      NaN   

         SecurityDelay  LateAircraftDelay  
3231732            NaN                NaN  
2005293            NaN                NaN  
1110113            NaN                NaN  
3304867            NaN                NaN  
621929             NaN                NaN  
...                ...                ...  
1669030            NaN                NaN  
4214149            0.0               22.0  
4506188            NaN                NaN  
1752876            NaN                NaN  
6961635            NaN                NaN  

[7009728 rows x 29 columns]

In [11]:
#mostrar una columna
df.DepTime

0          2003.0
1           754.0
2           628.0
3           926.0
4          1829.0
            ...  
7009723    1002.0
7009724     834.0
7009725     655.0
7009726    1251.0
7009727    1110.0
Name: DepTime, Length: 7009728, dtype: float64

In [13]:
#mostrar los tipos de datos
df.dtypes

Year                   int64
Month                  int64
DayofMonth             int64
DayOfWeek              int64
DepTime              float64
CRSDepTime             int64
ArrTime              float64
CRSArrTime             int64
UniqueCarrier         object
FlightNum              int64
TailNum               object
ActualElapsedTime    float64
CRSElapsedTime       float64
AirTime              float64
ArrDelay             float64
DepDelay             float64
Origin                object
Dest                  object
Distance               int64
TaxiIn               float64
TaxiOut              float64
Cancelled              int64
CancellationCode      object
Diverted               int64
CarrierDelay         float64
WeatherDelay         float64
NASDelay             float64
SecurityDelay        float64
LateAircraftDelay    float64
dtype: object

In [14]:
#ver los datos
df.values

array([[2008, 1, 3, ..., nan, nan, nan],
       [2008, 1, 3, ..., nan, nan, nan],
       [2008, 1, 3, ..., nan, nan, nan],
       ...,
       [2008, 12, 13, ..., nan, nan, nan],
       [2008, 12, 13, ..., nan, nan, nan],
       [2008, 12, 13, ..., nan, nan, nan]], dtype=object)

In [15]:
#crear otro dataframe
df2=df.head(10)

In [16]:
df2.head(10)

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0  2008      1           3          4   2003.0        1955   2211.0   
1  2008      1           3          4    754.0         735   1002.0   
2  2008      1           3          4    628.0         620    804.0   
3  2008      1           3          4    926.0         930   1054.0   
4  2008      1           3          4   1829.0        1755   1959.0   
5  2008      1           3          4   1940.0        1915   2121.0   
6  2008      1           3          4   1937.0        1830   2037.0   
7  2008      1           3          4   1039.0        1040   1132.0   
8  2008      1           3          4    617.0         615    652.0   
9  2008      1           3          4   1620.0        1620   1639.0   

   CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
0        2225            WN        335  ...    4.0      8.0          0   
1        1000            WN       3231  ...    5.0     10.0          0   
2         750            WN        448  ...    3.0     17.0          0   
3        1100            WN       1746  ...    3.0      7.0          0   
4        1925            WN       3920  ...    3.0     10.0          0   
5        2110            WN        378  ...    4.0     10.0          0   
6        1940            WN        509  ...    3.0      7.0          0   
7        1150            WN        535  ...    7.0      7.0          0   
8         650            WN         11  ...    6.0     19.0          0   
9        1655            WN        810  ...    3.0      6.0          0   

   CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
0               NaN         0           NaN          NaN      NaN   
1               NaN         0           NaN          NaN      NaN   
2               NaN         0           NaN          NaN      NaN   
3               NaN         0           NaN          NaN      NaN   
4               NaN         0           2.0          0.0      0.0   
5               NaN         0           NaN          NaN      NaN   
6               NaN         0          10.0          0.0      0.0   
7               NaN         0           NaN          NaN      NaN   
8               NaN         0           NaN          NaN      NaN   
9               NaN         0           NaN          NaN      NaN   

   SecurityDelay  LateAircraftDelay  
0            NaN                NaN  
1            NaN                NaN  
2            NaN                NaN  
3            NaN                NaN  
4            0.0               32.0  
5            NaN                NaN  
6            0.0               47.0  
7            NaN                NaN  
8            NaN                NaN  
9            NaN                NaN  

[10 rows x 29 columns]

## filtrado de datos

In [2]:
#filtar una columna
df["ArrDelay"].head()

0   -14.0
1     2.0
2    14.0
3    -6.0
4    34.0
Name: ArrDelay, dtype: float64

In [3]:
#información de las primeras 10 filas
df[0:10]

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0  2008      1           3          4   2003.0        1955   2211.0   
1  2008      1           3          4    754.0         735   1002.0   
2  2008      1           3          4    628.0         620    804.0   
3  2008      1           3          4    926.0         930   1054.0   
4  2008      1           3          4   1829.0        1755   1959.0   
5  2008      1           3          4   1940.0        1915   2121.0   
6  2008      1           3          4   1937.0        1830   2037.0   
7  2008      1           3          4   1039.0        1040   1132.0   
8  2008      1           3          4    617.0         615    652.0   
9  2008      1           3          4   1620.0        1620   1639.0   

   CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
0        2225            WN        335  ...    4.0      8.0          0   
1        1000            WN       3231  ...    5.0     10.0          0   
2         750            WN        448  ...    3.0     17.0          0   
3        1100            WN       1746  ...    3.0      7.0          0   
4        1925            WN       3920  ...    3.0     10.0          0   
5        2110            WN        378  ...    4.0     10.0          0   
6        1940            WN        509  ...    3.0      7.0          0   
7        1150            WN        535  ...    7.0      7.0          0   
8         650            WN         11  ...    6.0     19.0          0   
9        1655            WN        810  ...    3.0      6.0          0   

   CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
0               NaN         0           NaN          NaN      NaN   
1               NaN         0           NaN          NaN      NaN   
2               NaN         0           NaN          NaN      NaN   
3               NaN         0           NaN          NaN      NaN   
4               NaN         0           2.0          0.0      0.0   
5               NaN         0           NaN          NaN      NaN   
6               NaN         0          10.0          0.0      0.0   
7               NaN         0           NaN          NaN      NaN   
8               NaN         0           NaN          NaN      NaN   
9               NaN         0           NaN          NaN      NaN   

   SecurityDelay  LateAircraftDelay  
0            NaN                NaN  
1            NaN                NaN  
2            NaN                NaN  
3            NaN                NaN  
4            0.0               32.0  
5            NaN                NaN  
6            0.0               47.0  
7            NaN                NaN  
8            NaN                NaN  
9            NaN                NaN  

[10 rows x 29 columns]

In [17]:
#vuelos retrasados menos de 60 minutos
df[df["ArrDelay"]<60].head(5)

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0  2008      1           3          4   2003.0        1955   2211.0   
1  2008      1           3          4    754.0         735   1002.0   
2  2008      1           3          4    628.0         620    804.0   
3  2008      1           3          4    926.0         930   1054.0   
4  2008      1           3          4   1829.0        1755   1959.0   

   CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
0        2225            WN        335  ...    4.0      8.0          0   
1        1000            WN       3231  ...    5.0     10.0          0   
2         750            WN        448  ...    3.0     17.0          0   
3        1100            WN       1746  ...    3.0      7.0          0   
4        1925            WN       3920  ...    3.0     10.0          0   

   CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
0               NaN         0           NaN          NaN      NaN   
1               NaN         0           NaN          NaN      NaN   
2               NaN         0           NaN          NaN      NaN   
3               NaN         0           NaN          NaN      NaN   
4               NaN         0           2.0          0.0      0.0   

   SecurityDelay  LateAircraftDelay  
0            NaN                NaN  
1            NaN                NaN  
2            NaN                NaN  
3            NaN                NaN  
4            0.0               32.0  

[5 rows x 29 columns]

In [18]:
#vuelos retrasados más de 60 minutos
df[df["ArrDelay"]>60].head(5)

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
11  2008      1           3          4   1644.0        1510   1845.0   
30  2008      1           3          4   2107.0        1945   2334.0   
37  2008      1           3          4   1812.0        1650   1927.0   
49  2008      1           3          4   2245.0        1730   2354.0   
77  2008      1           3          4    958.0         900   1052.0   

    CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
11        1725            WN       1333  ...    6.0      8.0          0   
30        2230            WN        362  ...    6.0      7.0          0   
37        1815            WN        422  ...    6.0     11.0          0   
49        1850            WN        186  ...    3.0      7.0          0   
77         950            WN       1574  ...    4.0     14.0          0   

    CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
11               NaN         0           8.0          0.0      0.0   
30               NaN         0           5.0          0.0      0.0   
37               NaN         0           3.0          0.0      0.0   
49               NaN         0         282.0          0.0      0.0   
77               NaN         0           0.0          0.0      4.0   

    SecurityDelay  LateAircraftDelay  
11            0.0               72.0  
30            0.0               59.0  
37            0.0               69.0  
49            0.0               22.0  
77            0.0               58.0  

[5 rows x 29 columns]

In [19]:
#vuelos retrasados 60 minutos
df[df["ArrDelay"]==60].head(5)

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
96    2008      1           3          4   2039.0        1930    155.0   
423   2008      1           3          4   2117.0        2010   2355.0   
610   2008      1           3          4   1942.0        1840   2205.0   
1356  2008      1           3          4   1933.0        1835   1955.0   
3574  2008      1           4          5   1600.0        1510   2355.0   

      CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
96            55            WN       3940  ...    5.0     14.0          0   
423         2255            WN       1485  ...    4.0     10.0          0   
610         2105            WN       3332  ...    4.0      9.0          0   
1356        1855            WN        921  ...    2.0     10.0          0   
3574        2255            WN       3144  ...    5.0     13.0          0   

      CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
96                 NaN         0           0.0          0.0     22.0   
423                NaN         0           0.0          0.0      1.0   
610                NaN         0          60.0          0.0      0.0   
1356               NaN         0           0.0          0.0      3.0   
3574               NaN         0           5.0          0.0     10.0   

      SecurityDelay  LateAircraftDelay  
96              0.0               38.0  
423             0.0               59.0  
610             0.0                0.0  
1356            0.0               57.0  
3574            0.0               45.0  

[5 rows x 29 columns]

In [20]:
#vuelos que no se han retrasado una hora
df[df["ArrDelay"]!=60].head()

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0  2008      1           3          4   2003.0        1955   2211.0   
1  2008      1           3          4    754.0         735   1002.0   
2  2008      1           3          4    628.0         620    804.0   
3  2008      1           3          4    926.0         930   1054.0   
4  2008      1           3          4   1829.0        1755   1959.0   

   CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
0        2225            WN        335  ...    4.0      8.0          0   
1        1000            WN       3231  ...    5.0     10.0          0   
2         750            WN        448  ...    3.0     17.0          0   
3        1100            WN       1746  ...    3.0      7.0          0   
4        1925            WN       3920  ...    3.0     10.0          0   

   CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
0               NaN         0           NaN          NaN      NaN   
1               NaN         0           NaN          NaN      NaN   
2               NaN         0           NaN          NaN      NaN   
3               NaN         0           NaN          NaN      NaN   
4               NaN         0           2.0          0.0      0.0   

   SecurityDelay  LateAircraftDelay  
0            NaN                NaN  
1            NaN                NaN  
2            NaN                NaN  
3            NaN                NaN  
4            0.0               32.0  

[5 rows x 29 columns]

In [21]:
#vuelos que salen de Atlanta
df[df["Origin"]=="ATL"].head()

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
103149  2008      1          21          1   1207.0        1210   1346.0   
103572  2008      1          12          6   1458.0        1500   1622.0   
104019  2008      1          20          7   1403.0        1330   1625.0   
104124  2008      1          26          6   1629.0        1630   1832.0   
104485  2008      1           4          5   1336.0        1340   1501.0   

        CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
103149        1335            XE       2349  ...   11.0     13.0          0   
103572        1620            XE       2145  ...    6.0     17.0          0   
104019        1608            XE       1284  ...    6.0     32.0          0   
104124        1902            XE       1241  ...    9.0     15.0          0   
104485        1500            XE       2112  ...   12.0     12.0          0   

        CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
103149               NaN         0           NaN          NaN      NaN   
103572               NaN         0           NaN          NaN      NaN   
104019               NaN         0           0.0          0.0     17.0   
104124               NaN         0           NaN          NaN      NaN   
104485               NaN         0           NaN          NaN      NaN   

        SecurityDelay  LateAircraftDelay  
103149            NaN                NaN  
103572            NaN                NaN  
104019            0.0                0.0  
104124            NaN                NaN  
104485            NaN                NaN  

[5 rows x 29 columns]

In [22]:
#filtro combinado
df[(df["Origin"]=="ATL")&(df["ArrDelay"]>60)].head()

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
109189  2008      1          31          4   1217.0        1210   1511.0   
110375  2008      1          19          6   1241.0        1215   1735.0   
121229  2008      1           3          4   1421.0        1200   1526.0   
132768  2008      1           6          7   1315.0        1130   1410.0   
133549  2008      1           7          1   2040.0        1800   2156.0   

        CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
109189        1335            XE       2023  ...   21.0     60.0          0   
110375        1437            XE       1284  ...   12.0    178.0          0   
121229        1325            XE       2132  ...    9.0     13.0          0   
132768        1240            YV       7267  ...    3.0      6.0          0   
133549        1932            YV       2626  ...   12.0     28.0          0   

        CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
109189               NaN         0           0.0          0.0     96.0   
110375               NaN         0           0.0          0.0    164.0   
121229               NaN         0          17.0          0.0      0.0   
132768               NaN         0           0.0          0.0     90.0   
133549               NaN         0         144.0          0.0      0.0   

        SecurityDelay  LateAircraftDelay  
109189            0.0                0.0  
110375            0.0               14.0  
121229            0.0              104.0  
132768            0.0                0.0  
133549            0.0                0.0  

[5 rows x 29 columns]

In [24]:
#filtrar con una lista
df[df.Origin.isin(["HOU","ATL"])].head()

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
3269  2008      1           4          5   1910.0        1910   2025.0   
3270  2008      1           4          5   1345.0        1345   1453.0   
3271  2008      1           4          5    736.0         735    839.0   
3272  2008      1           4          5   1603.0        1550   1647.0   
3273  2008      1           4          5   2105.0        2105   2151.0   

      CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
3269        2025            WN        823  ...    6.0     11.0          0   
3270        1500            WN        901  ...    3.0     14.0          0   
3271         850            WN        957  ...    3.0      9.0          0   
3272        1635            WN        231  ...    5.0     10.0          0   
3273        2150            WN        570  ...    7.0     11.0          0   

      CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
3269               NaN         0           NaN          NaN      NaN   
3270               NaN         0           NaN          NaN      NaN   
3271               NaN         0           NaN          NaN      NaN   
3272               NaN         0           NaN          NaN      NaN   
3273               NaN         0           NaN          NaN      NaN   

      SecurityDelay  LateAircraftDelay  
3269            NaN                NaN  
3270            NaN                NaN  
3271            NaN                NaN  
3272            NaN                NaN  
3273            NaN                NaN  

[5 rows x 29 columns]

In [28]:
#filtrar nulos
df[pd.isna(df["ArrDelay"])].head()

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
178  2008      1           3          4      NaN         700      NaN   
373  2008      1           3          4      NaN        1100      NaN   
399  2008      1           3          4      NaN         905      NaN   
401  2008      1           3          4      NaN        1620      NaN   
415  2008      1           3          4      NaN        1930      NaN   

     CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
178         830            WN        126  ...    NaN      NaN          1   
373        1215            WN       1146  ...    NaN      NaN          1   
399        1025            WN        469  ...    NaN      NaN          1   
401        1740            WN        618  ...    NaN      NaN          1   
415        2035            WN       2528  ...    NaN      NaN          1   

     CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
178                 A         0           NaN          NaN      NaN   
373                 A         0           NaN          NaN      NaN   
399                 A         0           NaN          NaN      NaN   
401                 C         0           NaN          NaN      NaN   
415                 A         0           NaN          NaN      NaN   

     SecurityDelay  LateAircraftDelay  
178            NaN                NaN  
373            NaN                NaN  
399            NaN                NaN  
401            NaN                NaN  
415            NaN                NaN  

[5 rows x 29 columns]

In [29]:
#saber cuántas filas son nulas
len(df[pd.isna(df["ArrDelay"])])

154699

## transformaciones

In [30]:
#calcular una columna a partir de otra
df["HoursDelay"]=round(df["ArrDelay"]/60)

In [31]:
df["HoursDelay"].head()

0   -0.0
1    0.0
2    0.0
3   -0.0
4    1.0
Name: HoursDelay, dtype: float64

In [32]:
#eliminar una comuna
del(df["HoursDelay"])

In [33]:
#comprobar la eliminación
df["HoursDelay"].head()

KeyError: 'HoursDelay'

In [36]:
#eliminar más de una columna
df.drop(["Diverted", "Cancelled","Year"], axis=1)
#esto no guarda los cambios en el set de datos

Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0            1           3          4   2003.0        1955   2211.0   
1            1           3          4    754.0         735   1002.0   
2            1           3          4    628.0         620    804.0   
3            1           3          4    926.0         930   1054.0   
4            1           3          4   1829.0        1755   1959.0   
...        ...         ...        ...      ...         ...      ...   
7009723     12          13          6   1002.0         959   1204.0   
7009724     12          13          6    834.0         835   1021.0   
7009725     12          13          6    655.0         700    856.0   
7009726     12          13          6   1251.0        1240   1446.0   
7009727     12          13          6   1110.0        1103   1413.0   

         CRSArrTime UniqueCarrier  FlightNum TailNum  ...  Dest  Distance  \
0              2225            WN        335  N712SW  ...   TPA       810   
1              1000            WN       3231  N772SW  ...   TPA       810   
2               750            WN        448  N428WN  ...   BWI       515   
3              1100            WN       1746  N612SW  ...   BWI       515   
4              1925            WN       3920  N464WN  ...   BWI       515   
...             ...           ...        ...     ...  ...   ...       ...   
7009723        1150            DL       1636  N646DL  ...   IAD       533   
7009724        1023            DL       1637  N908DL  ...   SAT       874   
7009725         856            DL       1638  N671DN  ...   ATL       545   
7009726        1437            DL       1639  N646DL  ...   ATL       533   
7009727        1418            DL       1641  N908DL  ...   ATL       874   

         TaxiIn  TaxiOut  CancellationCode CarrierDelay WeatherDelay  \
0           4.0      8.0               NaN          NaN          NaN   
1           5.0     10.0               NaN          NaN          NaN   
2           3.0     17.0               NaN          NaN          NaN   
3           3.0      7.0               NaN          NaN          NaN   
4           3.0     10.0               NaN          2.0          0.0   
...         ...      ...               ...          ...          ...   
7009723     6.0     45.0               NaN          NaN          NaN   
7009724     5.0     23.0               NaN          NaN          NaN   
7009725    24.0     12.0               NaN          NaN          NaN   
7009726    13.0     13.0               NaN          NaN          NaN   
7009727     8.0     11.0               NaN          NaN          NaN   

         NASDelay  SecurityDelay  LateAircraftDelay  
0             NaN            NaN                NaN  
1             NaN            NaN                NaN  
2             NaN            NaN                NaN  
3             NaN            NaN                NaN  
4             0.0            0.0               32.0  
...           ...            ...                ...  
7009723       NaN            NaN                NaN  
7009724       NaN            NaN                NaN  
7009725       NaN            NaN                NaN  
7009726       NaN            NaN                NaN  
7009727       NaN            NaN                NaN  

[7009728 rows x 26 columns]

In [37]:
#eliminar más de una columna y guardar los cambios
df2=df.drop(["Diverted", "Cancelled","Year"], axis=1)

In [ ]:
#otra forma es decirle que elimine las columnas directamane del data set
#df.drop(["Diverted", "Cancelled","Year"], axis=1, inplace=True)

In [38]:
#eliminar la fila cero
df.drop(0)

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
1        2008      1           3          4    754.0         735   1002.0   
2        2008      1           3          4    628.0         620    804.0   
3        2008      1           3          4    926.0         930   1054.0   
4        2008      1           3          4   1829.0        1755   1959.0   
5        2008      1           3          4   1940.0        1915   2121.0   
...       ...    ...         ...        ...      ...         ...      ...   
7009723  2008     12          13          6   1002.0         959   1204.0   
7009724  2008     12          13          6    834.0         835   1021.0   
7009725  2008     12          13          6    655.0         700    856.0   
7009726  2008     12          13          6   1251.0        1240   1446.0   
7009727  2008     12          13          6   1110.0        1103   1413.0   

         CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
1              1000            WN       3231  ...    5.0     10.0          0   
2               750            WN        448  ...    3.0     17.0          0   
3              1100            WN       1746  ...    3.0      7.0          0   
4              1925            WN       3920  ...    3.0     10.0          0   
5              2110            WN        378  ...    4.0     10.0          0   
...             ...           ...        ...  ...    ...      ...        ...   
7009723        1150            DL       1636  ...    6.0     45.0          0   
7009724        1023            DL       1637  ...    5.0     23.0          0   
7009725         856            DL       1638  ...   24.0     12.0          0   
7009726        1437            DL       1639  ...   13.0     13.0          0   
7009727        1418            DL       1641  ...    8.0     11.0          0   

         CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
1                     NaN         0           NaN          NaN      NaN   
2                     NaN         0           NaN          NaN      NaN   
3                     NaN         0           NaN          NaN      NaN   
4                     NaN         0           2.0          0.0      0.0   
5                     NaN         0           NaN          NaN      NaN   
...                   ...       ...           ...          ...      ...   
7009723               NaN         0           NaN          NaN      NaN   
7009724               NaN         0           NaN          NaN      NaN   
7009725               NaN         0           NaN          NaN      NaN   
7009726               NaN         0           NaN          NaN      NaN   
7009727               NaN         0           NaN          NaN      NaN   

         SecurityDelay  LateAircraftDelay  
1                  NaN                NaN  
2                  NaN                NaN  
3                  NaN                NaN  
4                  0.0               32.0  
5                  NaN                NaN  
...                ...                ...  
7009723            NaN                NaN  
7009724            NaN                NaN  
7009725            NaN                NaN  
7009726            NaN                NaN  
7009727            NaN                NaN  

[7009727 rows x 29 columns]

In [39]:
#eliminar varias filas a la vez
df.drop(range(0,100))

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
100      2008      1           3          4    826.0         825    930.0   
101      2008      1           3          4   2118.0        2015   2224.0   
102      2008      1           3          4   1818.0        1740   1916.0   
103      2008      1           3          4    650.0         650    748.0   
104      2008      1           3          4   2146.0        2055   2250.0   
...       ...    ...         ...        ...      ...         ...      ...   
7009723  2008     12          13          6   1002.0         959   1204.0   
7009724  2008     12          13          6    834.0         835   1021.0   
7009725  2008     12          13          6    655.0         700    856.0   
7009726  2008     12          13          6   1251.0        1240   1446.0   
7009727  2008     12          13          6   1110.0        1103   1413.0   

         CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
100             925            WN        136  ...    2.0     16.0          0   
101            2115            WN        219  ...    3.0     17.0          0   
102            1840            WN        391  ...    2.0     10.0          0   
103             750            WN        670  ...    3.0      8.0          0   
104            2155            WN        815  ...    3.0     13.0          0   
...             ...           ...        ...  ...    ...      ...        ...   
7009723        1150            DL       1636  ...    6.0     45.0          0   
7009724        1023            DL       1637  ...    5.0     23.0          0   
7009725         856            DL       1638  ...   24.0     12.0          0   
7009726        1437            DL       1639  ...   13.0     13.0          0   
7009727        1418            DL       1641  ...    8.0     11.0          0   

         CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
100                   NaN         0           NaN          NaN      NaN   
101                   NaN         0          17.0          0.0      6.0   
102                   NaN         0          20.0          0.0      0.0   
103                   NaN         0           NaN          NaN      NaN   
104                   NaN         0           4.0          0.0      4.0   
...                   ...       ...           ...          ...      ...   
7009723               NaN         0           NaN          NaN      NaN   
7009724               NaN         0           NaN          NaN      NaN   
7009725               NaN         0           NaN          NaN      NaN   
7009726               NaN         0           NaN          NaN      NaN   
7009727               NaN         0           NaN          NaN      NaN   

         SecurityDelay  LateAircraftDelay  
100                NaN                NaN  
101                0.0               46.0  
102                0.0               16.0  
103                NaN                NaN  
104                0.0               47.0  
...                ...                ...  
7009723            NaN                NaN  
7009724            NaN                NaN  
7009725            NaN                NaN  
7009726            NaN                NaN  
7009727            NaN                NaN  

[7009628 rows x 29 columns]

In [40]:
#añadir filas
dfAtl=df[df.Origin=="ATL"]
dfHou=df[df.Origin=="HOU"]

In [41]:
#combinar los dataframe
dfNew=dfAtl.append(dfHou)

C:\Users\David\AppData\Local\Temp\ipykernel_11648\1207049344.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dfNew=dfAtl.append(dfHou)


In [42]:
dfNew.Origin

103149     ATL
103572     ATL
104019     ATL
104124     ATL
104485     ATL
          ... 
7003419    HOU
7004690    HOU
7005947    HOU
7007233    HOU
7008545    HOU
Name: Origin, Length: 470446, dtype: object

## group by

In [43]:
#agrupar por día de la semana y calcular el máximo retraso
df.groupby(by="DayOfWeek")["ArrDelay"].max()

DayOfWeek
1    1583.0
2    1951.0
3    1510.0
4    2453.0
5    1707.0
6    1525.0
7    2461.0
Name: ArrDelay, dtype: float64

In [44]:
#agrupar por día de la semana y calcular el mínimo retraso
df.groupby(by="DayOfWeek")["ArrDelay"].min()

DayOfWeek
1   -519.0
2    -89.0
3    -87.0
4   -129.0
5    -86.0
6    -91.0
7    -92.0
Name: ArrDelay, dtype: float64

In [45]:
#agrupar por día de la semana y calcular la cantidad
df.groupby(by="DayOfWeek")["ArrDelay"].count()

DayOfWeek
1    1013410
2    1005992
3    1016995
4    1011970
5    1008872
6     841663
7     956127
Name: ArrDelay, dtype: int64

In [46]:
#agrupar por día de la semana y mostrar un resumen
df.groupby(by="DayOfWeek")["ArrDelay"].describe()

count       mean        std    min   25%  50%   75%     max
DayOfWeek                                                                 
1          1013410.0   8.210850  38.013811 -519.0 -10.0 -2.0  12.0  1583.0
2          1005992.0   7.481208  38.361073  -89.0 -11.0 -3.0  11.0  1951.0
3          1016995.0   6.522017  36.024679  -87.0 -10.0 -3.0  10.0  1510.0
4          1011970.0   8.411599  37.397411 -129.0 -10.0 -1.0  12.0  2453.0
5          1008872.0  10.953440  40.252320  -86.0  -9.0  0.0  15.0  1707.0
6           841663.0   5.789666  37.163120  -91.0 -11.0 -3.0   9.0  1525.0
7           956127.0   9.495886  41.759296  -92.0 -10.0 -2.0  12.0  2461.0

In [48]:
#sacar el promedio por día de dos variables
df.groupby(by="DayOfWeek")["ArrDelay","DepDelay"].mean()

C:\Users\David\AppData\Local\Temp\ipykernel_11648\106494201.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(by="DayOfWeek")["ArrDelay","DepDelay"].mean()


ArrDelay   DepDelay
DayOfWeek                      
1           8.210850  10.269990
2           7.481208   8.976897
3           6.522017   8.289761
4           8.411599   9.772897
5          10.953440  12.158036
6           5.789666   8.645681
7           9.495886  11.568973

In [49]:
#sacar el rango por día
df.groupby(by="DayOfWeek")["ArrDelay","DepDelay"].max()-df.groupby(by="DayOfWeek")["ArrDelay","DepDelay"].min()

C:\Users\David\AppData\Local\Temp\ipykernel_11648\1111412098.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(by="DayOfWeek")["ArrDelay","DepDelay"].max()-df.groupby(by="DayOfWeek")["ArrDelay","DepDelay"].min()
C:\Users\David\AppData\Local\Temp\ipykernel_11648\1111412098.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(by="DayOfWeek")["ArrDelay","DepDelay"].max()-df.groupby(by="DayOfWeek")["ArrDelay","DepDelay"].min()


ArrDelay  DepDelay
DayOfWeek                    
1            2102.0    2086.0
2            2040.0    2013.0
3            1597.0    1589.0
4            2582.0    2528.0
5            1793.0    1802.0
6            1616.0    1600.0
7            2553.0    2524.0

In [51]:

dfAtlHou=df[df.Origin.isin(["ATL","HOU"])]

In [52]:
#para cada día de la semana los vuelos que salen de Atlanta y Houston y su media para
#comparar en cuál de las dos ciudades los vuelos llegan más retrasados y en qué día las diferencias son mayores
dfAtlHou.groupby(by=["DayOfWeek","Origin"])["ArrDelay"].mean()

DayOfWeek  Origin
1          ATL        9.123436
           HOU        6.356856
2          ATL        8.933587
           HOU        9.348112
3          ATL        8.809146
           HOU        9.073109
4          ATL       10.186501
           HOU       12.994016
5          ATL       14.797440
           HOU       11.036545
6          ATL        9.511662
           HOU        4.283933
7          ATL       13.798627
           HOU        7.045287
Name: ArrDelay, dtype: float64

In [53]:
#para cada día de la semana los vuelos que salen de Atlanta y Houston y su media para
#comparar en cuál de las dos ciudades los vuelos llegan más retrasados y en qué día
#cambiando el orden, la salida no es tan intuitiva
dfAtlHou.groupby(by=["Origin","DayOfWeek"])["ArrDelay"].mean()

Origin  DayOfWeek
ATL     1             9.123436
        2             8.933587
        3             8.809146
        4            10.186501
        5            14.797440
        6             9.511662
        7            13.798627
HOU     1             6.356856
        2             9.348112
        3             9.073109
        4            12.994016
        5            11.036545
        6             4.283933
        7             7.045287
Name: ArrDelay, dtype: float64

In [54]:
#se puede guardar el groupby
migrupo=dfAtlHou.groupby(by=["Origin","DayOfWeek"])["ArrDelay"].mean()

In [56]:
migrupo.describe()

count    14.000000
mean      9.664161
std       2.848236
min       4.283933
25%       8.840256
50%       9.235774
75%      10.824034
max      14.797440
Name: ArrDelay, dtype: float64

## tratar duplicados y perdidos

In [3]:
dfduplicado=df.append(df)

C:\Users\David\AppData\Local\Temp\ipykernel_10008\1699889978.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dfduplicado=df.append(df)


In [4]:
dfduplicado=dfduplicado.sample(frac=1)

In [5]:
dfclean=dfduplicado.drop_duplicates()

In [6]:
#comparar el núero de filas de los dataframe
len(dfclean)==len(df)

False

In [7]:
len(dfclean)

7009724

In [8]:
len(df)

7009728

In [9]:
#buscar duplicados en una columna
dfclean.drop_duplicates(subset="DayofMonth")

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
5780494  2008     10          18          6   1102.0        1107   1224.0   
4351497  2008      8           8          5   1543.0        1340   2000.0   
5332162  2008      9           2          2    550.0         600    656.0   
2773963  2008      5           1          4    750.0         755    900.0   
809727   2008      2          29          5   1108.0        1112   1153.0   
1217430  2008      3          15          6    736.0         740    914.0   
4812785  2008      8           6          3   1617.0        1600   2154.0   
2242731  2008      4          14          1   1503.0        1507   1638.0   
526636   2008      1          27          7   1356.0        1300   1602.0   
6055309  2008     11           5          3    655.0         700   1105.0   
2282622  2008      4           4          5   1020.0        1020   1126.0   
2072465  2008      4          23          3   1610.0        1612   1758.0   
5485245  2008     10          24          5   1020.0        1030   1140.0   
6941908  2008     12          26          5   1916.0        1910   2015.0   
6248410  2008     11           9          7    832.0         825   1419.0   
3392661  2008      6          22          7   1437.0        1245   1802.0   
3312769  2008      6          30          1   1525.0        1455   1815.0   
1228202  2008      3          19          3   1710.0        1710   1810.0   
3094198  2008      6          25          3   1027.0        1030   1155.0   
1350225  2008      3           3          1   1554.0        1545   1631.0   
4572055  2008      8          17          7    939.0         935   1059.0   
5184796  2008      9           7          7    956.0        1000   1106.0   
1234850  2008      3          20          4   1246.0        1230   1348.0   
4369973  2008      8          10          7   1023.0        1013   1153.0   
3762636  2008      7          31          4      NaN        1100      NaN   
6740873  2008     12          16          2   1359.0        1335   1540.0   
3593829  2008      6          11          3    614.0         615    824.0   
5235168  2008      9          12          5    759.0         804    855.0   
5105514  2008      9          28          7    853.0         854   1559.0   
3639460  2008      7          13          7   2010.0        2010   2130.0   
3363266  2008      6          21          6   1826.0        1832   2024.0   

         CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
5780494        1246            NW        229  ...   10.0     11.0          0   
4351497        1545            XE       2085  ...    6.0    154.0          0   
5332162         709            B6       1103  ...    3.0     15.0          0   
2773963         902            MQ       3307  ...    6.0     19.0          0   
809727         1210            OO       3823  ...    4.0     17.0          0   
1217430         910            WN       1953  ...   10.0     14.0          0   
4812785        2136            CO       1753  ...    7.0     28.0          0   
2242731        1655            9E       2935  ...    5.0     16.0          0   
526636         1530            AA       2325  ...    4.0     13.0          0   
6055309        1037            YV       2604  ...    9.0     11.0          0   
2282622        1110            AA       1099  ...    7.0     27.0          0   
2072465        1804            US        208  ...   11.0     13.0          0   
5485245        1148            XE       2871  ...   19.0     11.0          0   
6941908        2015            AA       2418  ...    4.0     14.0          0   
6248410        1400            F9        386  ...    6.0     14.0          0   
3392661        1615            MQ       3721  ...    5.0     16.0          0   
3312769        1808            DL        123  ...    5.0     19.0          0   
1228202        1800            WN       1684  ...    4.0     19.0          0   
3094198        1203     

In [10]:
#eliminar valores perdidos
df.dropna()

Empty DataFrame
Columns: [Year, Month, DayofMonth, DayOfWeek, DepTime, CRSDepTime, ArrTime, CRSArrTime, UniqueCarrier, FlightNum, TailNum, ActualElapsedTime, CRSElapsedTime, AirTime, ArrDelay, DepDelay, Origin, Dest, Distance, TaxiIn, TaxiOut, Cancelled, CancellationCode, Diverted, CarrierDelay, WeatherDelay, NASDelay, SecurityDelay, LateAircraftDelay]
Index: []

[0 rows x 29 columns]

In [11]:
#para que no hayan perdidos en una columna
df.dropna(subset=["CancellationCode"])

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
178      2008      1           3          4      NaN         700      NaN   
373      2008      1           3          4      NaN        1100      NaN   
399      2008      1           3          4      NaN         905      NaN   
401      2008      1           3          4      NaN        1620      NaN   
415      2008      1           3          4      NaN        1930      NaN   
...       ...    ...         ...        ...      ...         ...      ...   
7009455  2008     12          13          6      NaN         600      NaN   
7009464  2008     12          13          6      NaN        1930      NaN   
7009564  2008     12          13          6      NaN         700      NaN   
7009565  2008     12          13          6      NaN        1115      NaN   
7009648  2008     12          13          6      NaN        1020      NaN   

         CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
178             830            WN        126  ...    NaN      NaN          1   
373            1215            WN       1146  ...    NaN      NaN          1   
399            1025            WN        469  ...    NaN      NaN          1   
401            1740            WN        618  ...    NaN      NaN          1   
415            2035            WN       2528  ...    NaN      NaN          1   
...             ...           ...        ...  ...    ...      ...        ...   
7009455         815            DL       1211  ...    NaN      NaN          1   
7009464        2129            DL       1218  ...    NaN      NaN          1   
7009564        1035            DL       1421  ...    NaN      NaN          1   
7009565        1432            DL       1422  ...    NaN      NaN          1   
7009648        1126            DL       1532  ...    NaN      NaN          1   

         CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
178                     A         0           NaN          NaN      NaN   
373                     A         0           NaN          NaN      NaN   
399                     A         0           NaN          NaN      NaN   
401                     C         0           NaN          NaN      NaN   
415                     A         0           NaN          NaN      NaN   
...                   ...       ...           ...          ...      ...   
7009455                 A         0           NaN          NaN      NaN   
7009464                 A         0           NaN          NaN      NaN   
7009564                 A         0           NaN          NaN      NaN   
7009565                 A         0           NaN          NaN      NaN   
7009648                 A         0           NaN          NaN      NaN   

         SecurityDelay  LateAircraftDelay  
178                NaN                NaN  
373                NaN                NaN  
399                NaN                NaN  
401                NaN                NaN  
415                NaN                NaN  
...                ...                ...  
7009455            NaN                NaN  
7009464            NaN                NaN  
7009564            NaN                NaN  
7009565            NaN                NaN  
7009648            NaN                NaN  

[137434 rows x 29 columns]

## numpy

In [12]:
import numpy as np

In [13]:
valoraciones=np.array([[8,7,8,5],[2,6,8,1],[8,8,9,5]])
valoraciones

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

In [14]:
#acceder a los elementos
valoraciones[0][1]

7

In [15]:
valoraciones[0,1]

7

In [16]:
valoraciones2=np.array([[[8,7,8,5],[2,5,5,2]],[[2,6,8,4],[8,9,7,4]],[[8,8,9,3],[10,9,10,8]]])
valoraciones2

array([[[ 8,  7,  8,  5],
        [ 2,  5,  5,  2]],

       [[ 2,  6,  8,  4],
        [ 8,  9,  7,  4]],

       [[ 8,  8,  9,  3],
        [10,  9, 10,  8]]])

In [17]:
#aaceder a los elementos
valoraciones2[0,1,2]

5

In [18]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [19]:
#operaciones de array
valoraciones2+np.ones((3,2,4))

array([[[ 9.,  8.,  9.,  6.],
        [ 3.,  6.,  6.,  3.]],

       [[ 3.,  7.,  9.,  5.],
        [ 9., 10.,  8.,  5.]],

       [[ 9.,  9., 10.,  4.],
        [11., 10., 11.,  9.]]])

In [20]:
np.mean(valoraciones2)

6.458333333333333

In [21]:
#promedio de las primeras observaciones por filas
np.mean(valoraciones2, axis=0)

array([[6.        , 7.        , 8.33333333, 4.        ],
       [6.66666667, 7.66666667, 7.33333333, 4.66666667]])

In [22]:
#promedio de las primeras observaciones fila 0 y fila 1 de cada arreglo
np.mean(valoraciones2, axis=1)

array([[5. , 6. , 6.5, 3.5],
       [5. , 7.5, 7.5, 4. ],
       [9. , 8.5, 9.5, 5.5]])

In [23]:
#promedio de las primeras observaciones por fila de cada arreglo
np.mean(valoraciones2, axis=2)

array([[7.  , 3.5 ],
       [5.  , 7.  ],
       [7.  , 9.25]])

In [24]:
#pasar una lista a un arreglo con las dimensiones definidas
np.reshape([1,2,3,4,5,6,7,8,9,10,11,12],(3,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [25]:
#mediana
np.median(df["ArrDelay"])

nan

In [26]:
#arreglo aleatorio
np.random.rand(2,2)

array([[0.15144745, 0.12685617],
       [0.26348281, 0.30255436]])

## relaciones entre variables

In [10]:
np.corrcoef(df["ArrDelay"], df["DepDelay"])

array([[nan, nan],
       [nan, nan]])

In [11]:
#quitamos los na
df.dropna(inplace=True, subset=["ArrDelay","DepDelay"])

In [12]:
#ejecutamos de nuevo el coeficiente
np.corrcoef(df["ArrDelay"], df["DepDelay"])

array([[1.        , 0.93139078],
       [0.93139078, 1.        ]])

In [14]:
np.corrcoef([df["ArrDelay"], df["DepDelay"], df["DepTime"]])

array([[1.        , 0.93139078, 0.17827465],
       [0.93139078, 1.        , 0.20198125],
       [0.17827465, 0.20198125, 1.        ]])

In [24]:
#coeficiente de correlación para todos los datos
df.drop(inplace=True, columns = ["Year", "Cancelled", "Diverted"])

KeyError: "['Year', 'Cancelled', 'Diverted'] not found in axis"

In [25]:
df.corr()

Month  DayofMonth  DayOfWeek   DepTime  CRSDepTime  \
Month              1.000000   -0.000402  -0.005350 -0.010321   -0.008426   
DayofMonth        -0.000402    1.000000   0.004762 -0.001555   -0.001745   
DayOfWeek         -0.005350    0.004762   1.000000  0.005660    0.005666   
DepTime           -0.010321   -0.001555   0.005660  1.000000    0.968550   
CRSDepTime        -0.008426   -0.001745   0.005666  0.968550    1.000000   
ArrTime           -0.000377   -0.001505   0.003376  0.713081    0.697293   
CRSArrTime         0.000353   -0.001744   0.005569  0.791431    0.790820   
FlightNum          0.005307   -0.000283  -0.001439 -0.006075   -0.012513   
ActualElapsedTime -0.014061    0.000598   0.012929 -0.017070   -0.017184   
CRSElapsedTime    -0.006345    0.001384   0.015013 -0.013684   -0.011774   
AirTime           -0.012413    0.000950   0.013915 -0.023170   -0.021086   
ArrDelay          -0.042058    0.001607   0.010558  0.178275    0.116894   
DepDelay          -0.030498    0.003299   0.015425  0.201981    0.138850   
Distance          -0.005558    0.001363   0.016730 -0.016523   -0.012189   
TaxiIn             0.006904   -0.002933   0.010244 -0.042255   -0.047563   
TaxiOut           -0.016249   -0.000674  -0.007207  0.050649    0.039827   
CarrierDelay      -0.000232    0.000249   0.012319  0.001787   -0.053916   
WeatherDelay       0.005598    0.001249   0.006441  0.023042    0.006909   
NASDelay           0.013533    0.004114  -0.007274 -0.013341   -0.052253   
SecurityDelay     -0.003165   -0.000276   0.004513 -0.009065   -0.011447   
LateAircraftDelay  0.002176    0.009385   0.012024  0.205079    0.191594   
HoursDelay        -0.027464    0.002243   0.010866  0.163659    0.105099   

                    ArrTime  CRSArrTime  FlightNum  ActualElapsedTime  \
Month             -0.000377    0.000353   0.005307          -0.014061   
DayofMonth        -0.001505   -0.001744  -0.000283           0.000598   
DayOfWeek          0.003376    0.005569  -0.001439           0.012929   
DepTime            0.713081    0.791431  -0.006075          -0.017070   
CRSDepTime         0.697293    0.790820  -0.012513          -0.017184   
ArrTime            1.000000    0.862455  -0.017674           0.037625   
CRSArrTime         0.862455    1.000000  -0.029613           0.051469   
FlightNum         -0.017674   -0.029613   1.000000          -0.319347   
ActualElapsedTime  0.037625    0.051469  -0.319347           1.000000   
CRSElapsedTime     0.038654    0.056583  -0.326568           0.979875   
AirTime            0.030320    0.044016  -0.334444           0.984241   
ArrDelay           0.066021    0.113087   0.016603           0.093925   
DepDelay           0.073540    0.132823   0.009834           0.044380   
Distance           0.029023    0.046196  -0.348495           0.964521   
TaxiIn             0.007132   -0.006540  -0.009481           0.158444   
TaxiOut            0.049583    0.059792   0.016576           0.267801   
CarrierDelay      -0.058128   -0.053370   0.057192          -0.032919   
WeatherDelay      -0.020296    0.007568   0.064391          -0.013712   
NASDelay           0.019385   -0.010596   0.004423           0.203805   
SecurityDelay     -0.005345   -0.009237  -0.001206           0.000318   
LateAircraftDelay -0.009715    0.153406  -0.034556          -0.087003   
HoursDelay         0.051299    0.101990   0.024206           0.070913   

                   CRSElapsedTime  ...  DepDelay  Distance    TaxiIn  \
Month                   -0.006345  ... -0.030498 -0.005558  0.006904   
DayofMonth               0.001384  ...  0.003299  0.001363 -0.002933   
DayOfWeek                0.015013  ...  0.015425  0.016730  0.010244   
DepTime                 -0.013684  ...  0.201981 -0.016523 -0.042255   
CRSDepTime              -0.011774  ...  0.138850 -0.012189 -0.047563   
ArrTime                  0.038654  ...  0.073540  0.029023  0.007132   
CRSArrTime               0.056583  ...  0.132823  0.046196 -0.006540   
FlightNum        

In [28]:
#coeficiente de correlación para todos los datos
#df.drop(inplace=True, columns = ["Month"])
corr=round(df.corr(),3)
corr.style.background_gradient()